### ISSUE TITLE
alsa hw:1 playback

### ISSUE THREAD

**Issue by rogerdavis198** [RadioFreeAsia/GlassPlayer#2]
Will not switch to second alsa card for playback ie

--audio-device=ALSA hw:1

or am I using the wrong code

Thanks

**Comment by ElvishArtisan** [comment]
Try ```--audio-device=ALSA --alsa-device=hw:0```

**Comment by ElvishArtisan** [comment]
Or ```--audio-device=ALSA --alsa-device=hw:1``` as appropriate.

**Comment by rogerdavis198** [comment]
thank you
